name: 02-1 - Staging - Docker GHCR

on:
  workflow_call:
    inputs:
      docker-mode:
        required: false
        type: string
        default: ""

env:
  REGISTRY: ghcr.io
  USERNAME: ${{ github.actor }}
  IMAGE_NAME: ${{ github.repository }} #orga/repo

jobs:
  Display_Data:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Docker Registry: ${{ env.REGISTRY }}"
          echo "Docker Username: ${{ env.USERNAME }}"
          echo "Docker Image Name: ${{ env.IMAGE_NAME }}"
          echo "Docker Mode: ${{ inputs.docker-mode }}"